### PR TITLE
Allow download url to be modified via chef attribute

### PR DESCRIPTION
**Pull request by shanman190**
This Pull Request is to modify the cookbook to allow the capability of overriding the download url, so that the tarballs for Apache Solr and Apache Zookeeper can be downloaded from an alternate location.

### CODE REVIEW

**Comment by vkhatri** [comment]
@shanman190 Could you please elaborate the issue with keeping the checksums in libraries?

I am aware that currently cookbook does not allow custom url, issue #65 and i have local commits for it but not yet pushed (due to other issues). Setting default url value to `auto` and form the url in the recipe sound a better solution rather than maintaining node attributes.

PR looks good to me for other recipe related changes.

**Comment by shanman190** [comment]
@vkhatri I don't really see any issue with keeping it in the libraries section. I was thinking that it made sense to have each url be uniquely defined, so that if along the way the url was restructured it wouldn't end up with being a breaking change for older versions, then following along with that putting the checksums in the same place as those urls for consistency.

**Comment by vkhatri** [comment]
@shanman190 I have been updating other cookbooks to use `auto` url formation, you might want to take a look at cookbook https://github.com/vkhatri/chef-elasticsearch-cluster. It also help in keeping the nodes attributes minimal. Please let me know if this sound good to re base the PR.

**Comment by shanman190** [comment]
@vkhatri I took a look at your elasticsearch cookbook and I can get behind that. However, I do have a question regarding that. Why the use of the string literal 'auto' instead of using nil for the url attribute, then performing the same logic as the 'auto' path?

**Comment by vkhatri** [comment]
@shanman190 No reason for using auto, it is just i find setting a value to an attribute is somehow meaningful rather than setting it to nil.

Besides setting nil / auto, this way url formation happens in the recipe with limited attributes dependency and it is up to the user whether to set it or not.

I am going to update the cookbook today with some of the changes you introduced in this PR and push another version. If you still find something doesn't right, please let me know.

**Comment by shanman190** [comment]
@vkhatri One other addition would be to expose the checksum value to be used on a non-'auto' tarball url. That would allow new solr versions to be used and tested by users without having to modify or wait for an update to the cookbook.

**Comment by vkhatri** [comment]
@shanman190 Indeed, i added a comment about it in PR #70 

Idea is to allow users to provide `sha256sum` if cookbook does not have it.

**Comment by vkhatri** [comment]
@shanman190 Could you give it another shot?

**Comment by vkhatri** [comment]
Fixed in #65

**Comment by shanman190** [comment]
@vkhatri Sorry for not getting back to this. Looks great to me!

**Pull request closed without merging**
